name: Build and Push Docker Image

on:
  push:
    branches:
      - pr-590
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get short commit hash
      id: vars
      run: echo "GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/hcloud-cloud-controller-manager-dedicatednodes:latest -t ghcr.io/${{ github.repository_owner }}/hcloud-cloud-controller-manager-dedicatednodes:${{ env.GIT_COMMIT_SHORT }} -f dev/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/hcloud-cloud-controller-manager-dedicatednodes:latest
        docker push ghcr.io/${{ github.repository_owner }}/hcloud-cloud-controller-manager-dedicatednodes:${{ env.GIT_COMMIT_SHORT }}